# Generated by Django 3.2 on 2021-04-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('nick_name', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=128, null=True, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('session_id', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.CharField(default='driver', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
